on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  id-token: write

env: 
  AZURE_RG_NAME: rg-${{ vars.PROJECT_NAME }}-${{ vars.AZURE_RESOURCE_IDENTIFIER }}
  
jobs:

  persist_app_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Get Branch
      run: |
        branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
        echo ::set-env name=BRANCH::$branch

    - name: Update package.json
      run: |
        cat frontend/package.json |
        jq '.version="${{ github.ref_name }}"' > frontend/package.json
    
    - name: Change User
      run: |
        git config --local user.name "github-actions[bot]" &&
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
    - name: Commit and push
      run: |
        git add "frontend/package.json" &&
        git commit -m "[AUTO] Update frontend/package.json version to ${{ github.ref }}" &&
        git push origin HEAD:${{ env.BRANCH }}

  build_backend_artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Publish the app
      run: dotnet publish -c Release --property:PublishDir=publish
      working-directory: ./backend
    
    - name: Publish Backend Artifact
      id: publish-backend-artifact
      uses: actions/upload-artifact@v6
      with:
        name: ParkNDeploy.Api
        path: ./backend/ParkNDeploy.Api/publish
        if-no-files-found: error

  build_frontend_artifact:
    runs-on: ubuntu-latest
    needs: persist_app_version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build the app
      run: npm install && VITE_APP_VERSION=${{ github.ref_name }} npm run build
      working-directory: ./frontend

    - name: Ensure lints
      run: npm run lint
      working-directory: ./frontend
    
    - name: Publish Frontend Artifact
      id: publish-frontend-artifact
      uses: actions/upload-artifact@v6
      with:
        name: ParkNDeploy.Front
        path: ./frontend/dist
        if-no-files-found: error

  deploy_infrastructure:
    runs-on: ubuntu-latest

    environment: production

    outputs:
      appServiceName: ${{ steps.bicep_deploy.outputs.appServiceName }}
      staticWebAppName: ${{ steps.bicep_deploy.outputs.staticWebAppName }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Azure 
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 

    - name: Create resource group if not exists      
      run: |
        az group show --name ${{ env.AZURE_RG_NAME }} ||
        az group create --name ${{ env.AZURE_RG_NAME }} --location ${{ secrets.AZURE_REGION }}

    - name: Deploy bicep
      id: bicep_deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: ${{ secrets.AZURE_REGION }}
        template: ./infrastructure/main.bicep
        parameters: project=${{ vars.PROJECT_NAME }} location=${{ secrets.AZURE_REGION }} swaLocation=${{ secrets.AZURE_SWA_REGION }} identifier=${{ vars.AZURE_RESOURCE_IDENTIFIER }}
        resourceGroupName: ${{ env.AZURE_RG_NAME }}

  deploy_backend:
    runs-on: ubuntu-latest
    needs: [ deploy_infrastructure, build_backend_artifact ]
    environment: production

    steps:
      
    - name: Download Backend Artifact
      uses: actions/download-artifact@v7
      id: download-backend-artifact
      with:
        name: ParkNDeploy.Api

    - name: Login to Azure 
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    - name: Deploy backend to App Service
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ needs.deploy_infrastructure.outputs.appServiceName }}
        package: ${{ steps.download-backend-artifact.outputs.download-path }}
  
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [ deploy_infrastructure, build_frontend_artifact ]
    environment: production

    steps:

    - name: Download Frontend Artifact
      uses: actions/download-artifact@v7
      id: download-frontend-artifact
      with:
        name: ParkNDeploy.Front

    - name: Login to Azure 
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
  
    - name: Get Static Web App deployment token
      run: |      
        SWA_DEPLOYMENT_TOKEN=$(az staticwebapp secrets list -n ${{ needs.deploy_infrastructure.outputs.staticWebAppName }} -o tsv --query properties.apiKey)
        echo SWA_DEPLOYMENT_TOKEN=$SWA_DEPLOYMENT_TOKEN >> $GITHUB_ENV

    - name: Deploy frontend to Static Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_DEPLOYMENT_TOKEN }}
        app_location: ${{ steps.download-frontend-artifact.outputs.download-path }}
        action: upload
        skip_app_build: true
        skip_api_build: true